### ISSUE TITLE
Multiple level access on multiple accounts  

### ISSUE THREAD

**Issue by ryguy77** [e0c615c8e4d846ef817cd5063a88716c/AWSSSOHelper#1]
When using the -AllAccountRoles switch with multiple accounts and multiple access levels within those accounts. There seems to be a loop error; the last role name that is selected gets transposed to all of the accounts role names. This creates a no access error in line 171 since the role name is incorrect. 
Nice tool for SSO in powershell.

**Comment by e0c615c8e4d846ef817cd5063a88716c** [comment]
Hi, thanks for the bug report.  I recall encountering this bug and thought I pushed the fix - could you see if 0.0.19 (available from PS Gallery) still has the issue?

**Comment by ryguy77** [comment]
I am running version 0.0.19 still with the issue. 
Thank you for your support.

**Comment by e0c615c8e4d846ef817cd5063a88716c** [comment]
I've published 0.0.20, could you Update-Module and see if the issue persists?

**Comment by ryguy77** [comment]
Yes it is working now without any issues. Thank you for your help.

**Comment by e0c615c8e4d846ef817cd5063a88716c** [comment]
No problem at all - thanks for reporting.
