### ISSUE TITLE
Suggestion: Add Support for Additional Credential Output Options

### ISSUE THREAD

**Issue by X-Guardian** [e0c615c8e4d846ef817cd5063a88716c/AWSSSOHelper#5]
I have a [branch](https://github.com/X-Guardian/AWSSSOHelper/tree/Add-Additional-Outputs) that adds the following additional credential output options to the function:

- Output as an `Amazon.Runtime.SessionAWSCredentials` object for input to the `Credential` parameter of AWS PowerShell cmdlets.
- Output to the `$StoredAWSCredentials` shell variable for use by AWS PowerShell cmdlets.
- Written as profiles to the AWS SDK .NET encrypted credential file used by the AWS PowerShell cmdlets with a naming convention of `<AccountName>.<RoleName>`.
- Written as profiles to the AWS CLI ini-format credential file with a naming convention of `<AccountName>.<RoleName>`.
- Written to the AWS CLI environment variables: `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_SESSION_TOKEN` for use by the AWS CLI and other compatible tooling (Terraform, Sceptre).

Let me know if you would like me to create a Pull Request.

**Comment by e0c615c8e4d846ef817cd5063a88716c** [comment]
This is amazing - thanks again.  Are any of these breaking changes?

It would be great to incorporate if you wanted to submit a PR.

**Comment by X-Guardian** [comment]
No, it still supports the original two outputs. I'll raise a PR for you to take a look.
